package DateApp;


/**
* DateApp/DateInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 09 March 2017 03:52:59 o'clock GMT
*/

public interface DateInterfaceOperations 
{

  //define the getDateMethod(), which returns a string.
  String getDate ();
} // interface DateInterfaceOperations
