package DateApp;


/**
* DateApp/DateInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 09 March 2017 03:52:59 o'clock GMT
*/

abstract public class DateInterfaceHelper
{
  private static String  _id = "IDL:DateApp/DateInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DateApp.DateInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DateApp.DateInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DateApp.DateInterfaceHelper.id (), "DateInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DateApp.DateInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DateInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DateApp.DateInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DateApp.DateInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DateApp.DateInterface)
      return (DateApp.DateInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DateApp._DateInterfaceStub stub = new DateApp._DateInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DateApp.DateInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DateApp.DateInterface)
      return (DateApp.DateInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DateApp._DateInterfaceStub stub = new DateApp._DateInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
